name: Main
on:
  push:
    branches:
    - master
jobs:
  examples_template:
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/c3lang/c3c/releases/download/latest/c3-ubuntu-20.tar.gz
      - run: tar xvf c3-ubuntu-20.tar.gz
      - run: ls -la
      - run: ./c3c --version
